http:
  clients:
    - name: restfulBooker
      connectionTimeout: 5000
      connectionRequestTimeout: 4000
      socketTimeout: 3000
      url:
        baseUrl: localhost
        port: 3001
        protocol: http
      proxy:
        host: localhost
        port: 8080
      authentication:
        type: basic
        username: test
        password: testPass
    - name: testClient
      connectionTimeout: 5000
      connectionRequestTimeout: 4000
      socketTimeout: 3000
      url:
        baseUrl: localhost
        port: 3001
        protocol: http
kafka:
  bootstrap: development-kafka.de:9192
  consumer:
    - name: testtopic1
      useSASLAuthentication: true
      saslUsername: [[saslUser || Default User]]
      saslPassword: myPassword
    - name: topic2
  producer:
    - name: testConsumer1
      useSASLAuthentication: true
      saslUsername: myProducerUserName
      saslPassword: myProducerUserPass
database:
  - name: pvv
    url: jdbc:sqli://localhost:1529/abc:INFORMIXSERVER=info_server
    driver: com.informix.jdbc.IfxDriver
  - name: postgres
    url: jdbc:postgresql://dev.svc.kube.local:5432/dev
    driver: org.postgresql.Driver
application:
  resources:
    - name: db1
      path: /database/db1/
    - name: postgres
      path: /database/db2/
    - name: testdb
      path: /rest/db3/
custom:
  test: test
