sevenFacette:
  http:
    clients:
      restfulBooker:
        connectionTimeout: 5000
        connectionRequestTimeout: 4000
        socketTimeout: 3000
        url:
          baseUrl: localhost
          port: 3001
          protocol: http
        proxy:
          host: localhost
          port: 8080
        authentication:
          type: basic
          username: test
          password: testPass
      testClient:
        connectionTimeout: 3000
        connectionRequestTimeout: 5000
        socketTimeout: 7000
        url:
          baseUrl: some.url
          protocol: https
  kafka:
    bootstrapServer: development-kafka.de:9192
    consumer:
      testtopic1:
        useSASLAuthentication: false
        autoOffset: latest
      topic2:
        autoOffset: earliest
        bootstrapServer: development-kafka.de:9191
    producer:
      testProducer1:
        useSASLAuthentication: true
        saslUsername: myProducerUserName
        saslPassword: myProducerUserPass
        autoOffset: latest
  database:
    pvv:
      url: jdbc:sqli://localhost:1529/abc:INFORMIXSERVER=info_server
      driver: com.informix.jdbc.IfxDriver
    postgres:
      url: jdbc:postgresql://dev.svc.kube.local:5432/dev
      driver: org.postgresql.Driver
  application:
    resources:
      - name: db1
        path: /database/db1/
      - name: postgres
        path: /database/db2/
      - name: testdb
        path: /rest/db3/
  custom:
    test: test
