sevenFacette:
  http:
    clients:
      realWorld:
        connectionTimeout: 5000
        connectionRequestTimeout: 4000
        socketTimeout: 3000
        url:
          baseUrl: localhost
          port: 8080
          protocol: http
