services:
  - name: "testService"
    baseUrl: ""
    auth:
      type: BASIC
      username: ""
      password: ""
  - name: "testService 2"
    baseUrl: ""
    auth:
      type: BASIC
      username: ""
      password: ""
