
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: 7Facette

on:
  push:
        #    branches:
    #      - master
    tags:
      - 'v*'
    paths-ignore:
      - '*.md'
      - 'misc/**'
      - '.github/**'

jobs:
  build-core:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: print Java version
        run: java -version
      - name: Grant execute permission for gradlew
        run: chmod 0755 gradle && git add gradle
      - name: Build 7Facette core module with gradle
        run: gradle clean :core:build -x test
      - name: Get the version
        id: get_version
        run: echo ::set-env name=VERSION::${GITHUB_REF/refs\/tags\/}
      - name: Publish 7Facette core module to JFrog Bintray
        env:
          JFROG_ACTOR: ${{ secrets.JFROG_ACTOR }}
          JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
        # The GITHUB_REF tag comes in the format 'refs/tags/xxx'.
        # So if we split on '/' and take the 3rd value, we can get the release name.
        run: |
          ./gradlew -DVERSION=${{ env.VERSION }} :core:bintrayUpload
  build-web:
    needs: build-core
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: print Java version
        run: java -version
      - name: Grant execute permission for gradlew
        run: chmod 0755 gradlew && git add gradlew
      - name: Build 7Facette web module with gradle
        run: gradle clean :web:build -x test
      - name: Get the version
        id: get_version
        run: echo ::set-env name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Publish 7Facette web module to JFrog Bintray
        env:
          JFROG_ACTOR: ${{ secrets.JFROG_ACTOR }}
          JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
        run: |
          ./gradlew -DVERSION=${{ env.VERSION }} :web:bintrayUpload
      - name: Microsoft Teams Deploy Card
        uses: toko-bifrost/ms-teams-deploy-card@3.1.2
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          webhook-uri: ${{ secrets.WEB_URL }}
          show-on-start: false
          card-layout-exit: complete
          custom-facts: |
            - name: New 7Facette Version available
              value: Check out the new version ${{ env.VERSION }} of 7Facette -> https://github.com/p7s1-ctf/SevenFacette
      #- name: Send information to 7Facette channel
      #  uses: dhollerbach/actions.send-message-to-ms-teams@1.0.10
      #  with:
      #    webhook: ${{ secrets.WEB_URL }}
      #    message: 'Check out the new version ${{ env.VERSION }} of 7Facette -> https://github.com/p7s1-ctf/SevenFacette'

      #- uses: actions/setup-node@v1.1.0
      #  with:
      #    node-version: 12
      #    registry-url: https://registry.npmjs.org/
      #- run: cd core && npm install
      #- run: cd core && npm publish
      #  env:
      #    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
