name: Pull Request CI

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'misc/**'

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Print Java version
        run: java -version
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build core moudule with Gradle
        run: ./gradlew clean :core:build -x test
      - name: Bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-report.zip
      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: core-error-report
          path: build-report.zip
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Print Java version
        run: java -version
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build web module with Gradle
        run: ./gradlew clean :web:build -x test
      - name: Bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-report.zip
      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: web-error-report
          path: build-report.zip
