name: Pull Request CI

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'misc/**'
jobs:
  build-core:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: print Java version
        run: java -version
      - name: Grant execute permission for gradle
        run: chmod 0755 gradle && git add gradle
      - name: Build 7Facette core module with gradle
        run: gradle clean :core:build -x jsNodeTest
  build-web:
    needs: build-core
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: print Java version
        run: java -version
      - name: Grant execute permission for gradle
        run: chmod 0755 gradle && git add gradle
      - name: Build 7Facette web module with gradle
        uses: eskatos/gradle-command-action@v1
        with:
            arguments: build -x jsNodeTest
            gradle-version: 6.7
      #- name: Build 7Facette web module with gradle
      #  run: gradle clean :web:build -x jsNodeTest
